/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MyTokenV1__factory } from "./MyTokenV1__factory";
export { MyTokenV2__factory } from "./MyTokenV2__factory";
