/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as temp from "./temp";
export type { temp };
export type { MyTokenV1 } from "./MyTokenV1";
export type { MyTokenV2 } from "./MyTokenV2";
