/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type {
  UpgradedContract,
  UpgradedContractInterface,
} from "../UpgradedContract";

const _abi = [
  {
    inputs: [],
    name: "data",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getData",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_data",
        type: "uint256",
      },
    ],
    name: "increse",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_data",
        type: "uint256",
      },
    ],
    name: "setData",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5061021f806100206000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c80633bc5de30146100515780635b4b73a91461006f57806373d4a13a1461008b578063c4cb7af7146100a9575b600080fd5b6100596100c5565b604051610066919061010d565b60405180910390f35b61008960048036038101906100849190610159565b6100ce565b005b6100936100d8565b6040516100a0919061010d565b60405180910390f35b6100c360048036038101906100be9190610159565b6100de565b005b60008054905090565b8060008190555050565b60005481565b6001816100eb91906101b5565b60008190555050565b6000819050919050565b610107816100f4565b82525050565b600060208201905061012260008301846100fe565b92915050565b600080fd5b610136816100f4565b811461014157600080fd5b50565b6000813590506101538161012d565b92915050565b60006020828403121561016f5761016e610128565b5b600061017d84828501610144565b91505092915050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052601160045260246000fd5b60006101c0826100f4565b91506101cb836100f4565b92508282019050808211156101e3576101e2610186565b5b9291505056fea2646970667358221220665255c4226e91187c9a2a56bcd32849f697a464ac9ff328ff066954f0555ad064736f6c63430008180033";

type UpgradedContractConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: UpgradedContractConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class UpgradedContract__factory extends ContractFactory {
  constructor(...args: UpgradedContractConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      UpgradedContract & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): UpgradedContract__factory {
    return super.connect(runner) as UpgradedContract__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): UpgradedContractInterface {
    return new Interface(_abi) as UpgradedContractInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): UpgradedContract {
    return new Contract(address, _abi, runner) as unknown as UpgradedContract;
  }
}
