/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface HTLCInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getContract"
      | "getHashlock"
      | "haveContract"
      | "newContract"
      | "refund"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "HTLCNew" | "HTLCRefund" | "HTLCWithdraw"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getContract",
    values: [AddressLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getHashlock",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "haveContract",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "newContract",
    values: [AddressLike, BytesLike, BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "refund",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHashlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "haveContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "newContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace HTLCNewEvent {
  export type InputTuple = [
    contractId: BytesLike,
    sender: AddressLike,
    receiver: AddressLike,
    tokenContract: AddressLike,
    amount: BigNumberish,
    hashlock: BytesLike,
    timelock: BigNumberish
  ];
  export type OutputTuple = [
    contractId: string,
    sender: string,
    receiver: string,
    tokenContract: string,
    amount: bigint,
    hashlock: string,
    timelock: bigint
  ];
  export interface OutputObject {
    contractId: string;
    sender: string;
    receiver: string;
    tokenContract: string;
    amount: bigint;
    hashlock: string;
    timelock: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HTLCRefundEvent {
  export type InputTuple = [contractId: BytesLike];
  export type OutputTuple = [contractId: string];
  export interface OutputObject {
    contractId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HTLCWithdrawEvent {
  export type InputTuple = [contractId: BytesLike];
  export type OutputTuple = [contractId: string];
  export interface OutputObject {
    contractId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HTLC extends BaseContract {
  connect(runner?: ContractRunner | null): HTLC;
  waitForDeployment(): Promise<this>;

  interface: HTLCInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getContract: TypedContractMethod<
    [_sender: AddressLike, _receiver: AddressLike, _hashlock: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        string,
        bigint,
        boolean,
        boolean,
        string
      ] & {
        sender: string;
        receiver: string;
        tokenContract: string;
        amount: bigint;
        hashlock: string;
        timelock: bigint;
        withdrawn: boolean;
        refunded: boolean;
        preimage: string;
      }
    ],
    "view"
  >;

  getHashlock: TypedContractMethod<[_hashlock: BytesLike], [string], "view">;

  haveContract: TypedContractMethod<
    [_contractId: BytesLike],
    [boolean],
    "view"
  >;

  newContract: TypedContractMethod<
    [
      _receiver: AddressLike,
      _hashlock: BytesLike,
      _timelock: BigNumberish,
      _tokenContract: AddressLike,
      _amount: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  refund: TypedContractMethod<
    [_receiver: AddressLike, _hashlock: BytesLike],
    [boolean],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<
    [_sender: AddressLike, _hashlock: BytesLike, _preimage: BytesLike],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getContract"
  ): TypedContractMethod<
    [_sender: AddressLike, _receiver: AddressLike, _hashlock: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        string,
        bigint,
        boolean,
        boolean,
        string
      ] & {
        sender: string;
        receiver: string;
        tokenContract: string;
        amount: bigint;
        hashlock: string;
        timelock: bigint;
        withdrawn: boolean;
        refunded: boolean;
        preimage: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getHashlock"
  ): TypedContractMethod<[_hashlock: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "haveContract"
  ): TypedContractMethod<[_contractId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "newContract"
  ): TypedContractMethod<
    [
      _receiver: AddressLike,
      _hashlock: BytesLike,
      _timelock: BigNumberish,
      _tokenContract: AddressLike,
      _amount: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "refund"
  ): TypedContractMethod<
    [_receiver: AddressLike, _hashlock: BytesLike],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [_sender: AddressLike, _hashlock: BytesLike, _preimage: BytesLike],
    [boolean],
    "nonpayable"
  >;

  getEvent(
    key: "HTLCNew"
  ): TypedContractEvent<
    HTLCNewEvent.InputTuple,
    HTLCNewEvent.OutputTuple,
    HTLCNewEvent.OutputObject
  >;
  getEvent(
    key: "HTLCRefund"
  ): TypedContractEvent<
    HTLCRefundEvent.InputTuple,
    HTLCRefundEvent.OutputTuple,
    HTLCRefundEvent.OutputObject
  >;
  getEvent(
    key: "HTLCWithdraw"
  ): TypedContractEvent<
    HTLCWithdrawEvent.InputTuple,
    HTLCWithdrawEvent.OutputTuple,
    HTLCWithdrawEvent.OutputObject
  >;

  filters: {
    "HTLCNew(bytes32,address,address,address,uint256,bytes32,uint256)": TypedContractEvent<
      HTLCNewEvent.InputTuple,
      HTLCNewEvent.OutputTuple,
      HTLCNewEvent.OutputObject
    >;
    HTLCNew: TypedContractEvent<
      HTLCNewEvent.InputTuple,
      HTLCNewEvent.OutputTuple,
      HTLCNewEvent.OutputObject
    >;

    "HTLCRefund(bytes32)": TypedContractEvent<
      HTLCRefundEvent.InputTuple,
      HTLCRefundEvent.OutputTuple,
      HTLCRefundEvent.OutputObject
    >;
    HTLCRefund: TypedContractEvent<
      HTLCRefundEvent.InputTuple,
      HTLCRefundEvent.OutputTuple,
      HTLCRefundEvent.OutputObject
    >;

    "HTLCWithdraw(bytes32)": TypedContractEvent<
      HTLCWithdrawEvent.InputTuple,
      HTLCWithdrawEvent.OutputTuple,
      HTLCWithdrawEvent.OutputObject
    >;
    HTLCWithdraw: TypedContractEvent<
      HTLCWithdrawEvent.InputTuple,
      HTLCWithdrawEvent.OutputTuple,
      HTLCWithdrawEvent.OutputObject
    >;
  };
}
