/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { OriginalContract__factory } from "./OriginalContract__factory";
export { ProxyContract__factory } from "./ProxyContract__factory";
export { UpgradedContract__factory } from "./UpgradedContract__factory";
