/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { OriginalContract } from "./OriginalContract";
export type { ProxyContract } from "./ProxyContract";
export type { UpgradedContract } from "./UpgradedContract";
